"""Approval-gated self-improvement loop.

Inputs:
  - Latest InstantlyAnalyticsSnapshot (source of truth for KPIs).
  - Per-prompt-version rollup from local Engagement + GeneratedContent
    (used to label experiments and gate small samples).

Outputs:
  - A PromptRecommendation row (status='pending') describing the
    bottleneck, the proposed change, expected impact, and risk level.
  - On approval, the proposed_prompt text is written to the
    `prompt_configs` overlay (the same source `src/prompts/email.py`
    reads via `get_effective_prompt`). The PREVIOUS overlay is stashed
    on the recommendation row so the operator can roll back.

Nothing here ever pushes to Instantly, regenerates already-sent emails,
or applies a change without status='approved'. Approval is mediated by
the Engagement page UI.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import case, func, select

from src.db import session_scope
from src.models import (
    Engagement,
    GeneratedContent,
    InstantlyAnalyticsSnapshot,
    PromptRecommendation,
)
from src.prompts.email import DEFAULT_EMAIL_PROMPT_BODY
from src.prompts.loader import get_effective_prompt, save_overlay

log = logging.getLogger(__name__)

# Default benchmarks. Override per-call from the UI if needed.
DEFAULT_OPEN_RATE_TARGET = 0.30
DEFAULT_REPLY_RATE_TARGET = 0.03
DEFAULT_BOUNCE_RATE_MAX = 0.03
MIN_SAMPLE_FOR_RECOMMENDATION = 50


@dataclass
class MetricSet:
    """Parsed metrics from the latest analytics snapshot."""
    contacted: int
    sent: int
    opens: int
    replies: int
    bounces: int
    open_rate: float
    reply_rate: float
    bounce_rate: float
    sample_size: int  # sent-emails denominator the rates were computed against

    @classmethod
    def from_snapshot(cls, snap: dict[str, Any]) -> "MetricSet":
        sent = int(snap.get("emails_sent_count") or 0)
        opens = int(snap.get("open_count") or 0)
        replies = int(snap.get("reply_count") or 0)
        bounces = int(snap.get("bounced_count") or 0)
        denom = sent if sent > 0 else 1
        return cls(
            contacted=int(snap.get("contacted_count") or 0),
            sent=sent,
            opens=opens,
            replies=replies,
            bounces=bounces,
            open_rate=opens / denom,
            reply_rate=replies / denom,
            bounce_rate=bounces / denom,
            sample_size=sent,
        )


@dataclass
class Diagnosis:
    bottleneck: str                      # open_rate|reply_rate|bounce_rate|delivery|none
    channel: Optional[str]               # email | None
    diagnosis: str                       # human prose
    current_metric_label: str
    current_metric_value: float
    target_metric_value: float
    recommended_change: str              # what to do
    expected_impact: str
    risk_level: str                      # low | medium | high
    proposed_prompt: Optional[str]       # full prompt text, only for prompt-changing recs
    previous_prompt_snapshot: Optional[str]
    sample_size: int
    low_confidence: bool


# ---------------------------------------------------------------------------
# Prompt edit templates — generated by hand, not by an LLM. Each one appends
# a short directive to the END of the current overlay so the user can read
# the diff in the approval box and the existing prompt body stays intact.
# ---------------------------------------------------------------------------

_OPEN_RATE_ADDENDUM = """\

# OPEN-RATE FIX — added by self-improvement loop
Subject lines have been underperforming on open rate. Tighten as follows:
- Subject under 4 words. Prefer 2–3.
- Reference ONE concrete entity (company, product, role) — not a category.
- Avoid generic angles ("quick question", "intro", "checking in", "your team").
- Lowercase preferred. No emoji, no punctuation.

BAD subjects (do not use): "Outbound help", "quick question", "your sales team", "intro".
GOOD subjects: "servicenow play", "10 open sdrs", "ericsson fit", "telco outage angle".
"""

_REPLY_RATE_ADDENDUM = """\

# REPLY-RATE FIX — added by self-improvement loop
Body copy has been underperforming on reply rate. Tighten as follows:
- Cut every sentence that doesn't name a specific company, role, or signal.
- CTA must invite a ONE-WORD reply ("yes", "send it", "interested?"). Never propose a call or meeting time.
- Lead with a CONCRETE value comparison (cost vs in-house SDR, meetings next week, specific volume).
- Body length: 50–80 words. Anything longer reads like a vendor email.
- Drop hedging phrases ("might be a fit", "if you're open to...", "no worries if not").
"""


def _build_email_open_rate_prompt(current: str) -> str:
    return current.rstrip() + "\n" + _OPEN_RATE_ADDENDUM


def _build_email_reply_rate_prompt(current: str) -> str:
    return current.rstrip() + "\n" + _REPLY_RATE_ADDENDUM


# ---------------------------------------------------------------------------
# Diagnosis
# ---------------------------------------------------------------------------

def diagnose(
    metrics: MetricSet,
    *,
    open_rate_target: float = DEFAULT_OPEN_RATE_TARGET,
    reply_rate_target: float = DEFAULT_REPLY_RATE_TARGET,
    bounce_rate_max: float = DEFAULT_BOUNCE_RATE_MAX,
    contacted_expected: int | None = None,
    low_confidence_override: bool = False,
) -> Diagnosis:
    """Pick the worst-performing bottleneck and draft a recommendation.

    Priority:
      1. Bounce rate over max → data-hygiene action (NOT a prompt change).
      2. Delivery count well below expected → sync/delivery investigation.
      3. Open rate below target → subject-line addendum.
      4. Reply rate below target → body/CTA addendum.
      5. Everything green → no recommendation.

    Returns a Diagnosis even when below the min-sample threshold; the
    caller checks `low_confidence` and labels the UI accordingly.
    """
    sample_size = metrics.sample_size
    low_confidence = (
        sample_size < MIN_SAMPLE_FOR_RECOMMENDATION
    ) or low_confidence_override

    # 1) Bounce — data hygiene, never a prompt change.
    if metrics.sent > 0 and metrics.bounce_rate > bounce_rate_max:
        return Diagnosis(
            bottleneck="bounce_rate",
            channel=None,
            diagnosis=(
                f"Bounce rate is {metrics.bounce_rate * 100:.1f}% "
                f"(target ≤ {bounce_rate_max * 100:.1f}%). "
                "List quality / verification is the issue, not the copy."
            ),
            current_metric_label="Bounce rate",
            current_metric_value=metrics.bounce_rate,
            target_metric_value=bounce_rate_max,
            recommended_change=(
                "Run all unverified leads through the email verifier before "
                "the next push (Settings → Verify cache). Strip catch-all "
                "domains. Do NOT change the prompt — bounces are not a copy "
                "problem."
            ),
            expected_impact="Bounce rate drops below target within one send cycle.",
            risk_level="low",
            proposed_prompt=None,
            previous_prompt_snapshot=None,
            sample_size=sample_size,
            low_confidence=low_confidence,
        )

    # 2) Delivery — sequence-start count well below expected.
    if (
        contacted_expected is not None
        and contacted_expected > 0
        and metrics.contacted < int(contacted_expected * 0.85)
    ):
        return Diagnosis(
            bottleneck="delivery",
            channel=None,
            diagnosis=(
                f"Instantly has {metrics.contacted} sequence-started leads, "
                f"but the local DB expected ~{contacted_expected}. Likely "
                "causes: leads in the DB with no Instantly push, paused/"
                "stopped subseqs, or rate-limited campaign."
            ),
            current_metric_label="Sequences started",
            current_metric_value=float(metrics.contacted),
            target_metric_value=float(contacted_expected),
            recommended_change=(
                "Investigate the campaign in Instantly: confirm it's active, "
                "check daily send caps, and re-push leads with delivery_status "
                "= NULL. Do NOT change the prompt."
            ),
            expected_impact="Sequence-started count converges to local sent count.",
            risk_level="low",
            proposed_prompt=None,
            previous_prompt_snapshot=None,
            sample_size=sample_size,
            low_confidence=low_confidence,
        )

    # 3) Open rate — subject lines.
    if metrics.sent > 0 and metrics.open_rate < open_rate_target:
        current = get_effective_prompt("email", DEFAULT_EMAIL_PROMPT_BODY)
        proposed = _build_email_open_rate_prompt(current)
        return Diagnosis(
            bottleneck="open_rate",
            channel="email",
            diagnosis=(
                f"Open rate is {metrics.open_rate * 100:.1f}% "
                f"(target {open_rate_target * 100:.0f}%). Subject lines or "
                "targeting angle are weak."
            ),
            current_metric_label="Open rate",
            current_metric_value=metrics.open_rate,
            target_metric_value=open_rate_target,
            recommended_change=(
                "Append a SUBJECT-LINE addendum to the email prompt: enforce "
                "≤4 words, one concrete entity, lowercase, no generic angles. "
                "Only affects FUTURE generated emails."
            ),
            expected_impact=(
                f"Open rate +5 to +10 percentage points within ~{MIN_SAMPLE_FOR_RECOMMENDATION} "
                "new sends. Already-sent emails are untouched."
            ),
            risk_level="medium",
            proposed_prompt=proposed,
            previous_prompt_snapshot=current,
            sample_size=sample_size,
            low_confidence=low_confidence,
        )

    # 4) Reply rate — body / CTA.
    if metrics.sent > 0 and metrics.reply_rate < reply_rate_target:
        current = get_effective_prompt("email", DEFAULT_EMAIL_PROMPT_BODY)
        proposed = _build_email_reply_rate_prompt(current)
        return Diagnosis(
            bottleneck="reply_rate",
            channel="email",
            diagnosis=(
                f"Open rate is healthy ({metrics.open_rate * 100:.1f}%) but "
                f"reply rate is {metrics.reply_rate * 100:.2f}% "
                f"(target {reply_rate_target * 100:.0f}%). Body copy or CTA "
                "is the bottleneck."
            ),
            current_metric_label="Reply rate",
            current_metric_value=metrics.reply_rate,
            target_metric_value=reply_rate_target,
            recommended_change=(
                "Append a BODY/CTA addendum to the email prompt: tighten "
                "length to 50–80 words, force one-word CTA, drop hedging. "
                "Only affects FUTURE generated emails."
            ),
            expected_impact=(
                "Reply rate +1 to +2 percentage points on subsequent sends. "
                "Already-sent emails are untouched."
            ),
            risk_level="medium",
            proposed_prompt=proposed,
            previous_prompt_snapshot=current,
            sample_size=sample_size,
            low_confidence=low_confidence,
        )

    return Diagnosis(
        bottleneck="none",
        channel=None,
        diagnosis="All metrics meet or exceed the configured targets. No change recommended.",
        current_metric_label="Reply rate",
        current_metric_value=metrics.reply_rate,
        target_metric_value=reply_rate_target,
        recommended_change="No change recommended.",
        expected_impact="—",
        risk_level="low",
        proposed_prompt=None,
        previous_prompt_snapshot=None,
        sample_size=sample_size,
        low_confidence=low_confidence,
    )


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def save_recommendation(diag: Diagnosis, *, status: str = "pending") -> int:
    """Persist a Diagnosis as a PromptRecommendation row. Returns row id."""
    with session_scope() as session:
        rec = PromptRecommendation(
            bottleneck=diag.bottleneck,
            channel=diag.channel,
            diagnosis=diag.diagnosis,
            current_metric_label=diag.current_metric_label,
            current_metric_value=float(diag.current_metric_value),
            target_metric_value=float(diag.target_metric_value),
            recommended_change=diag.recommended_change,
            expected_impact=diag.expected_impact,
            risk_level=diag.risk_level,
            proposed_prompt=diag.proposed_prompt,
            previous_prompt_snapshot=diag.previous_prompt_snapshot,
            sample_size=int(diag.sample_size),
            low_confidence=bool(diag.low_confidence),
            status=status,
        )
        session.add(rec)
        session.flush()
        return int(rec.id)


def approve_recommendation(rec_id: int, *, approved_by: str) -> dict[str, Any]:
    """Approve a recommendation and apply the prompt change (if any).

    Only flips status to 'approved' and writes the proposed prompt text
    to the prompt_configs overlay. NEVER touches already-sent emails or
    Instantly. The previous overlay is already stashed on the row, so
    rollback is a separate action that copies previous_prompt_snapshot
    back into the overlay.
    """
    with session_scope() as session:
        rec = session.get(PromptRecommendation, rec_id)
        if rec is None:
            raise ValueError(f"Recommendation {rec_id} not found")
        if rec.status == "approved":
            return {"id": rec_id, "status": "approved", "already": True}
        rec.status = "approved"
        rec.approved_by = approved_by
        rec.approved_at = datetime.utcnow()
        channel = rec.channel
        proposed = rec.proposed_prompt

    # Write outside the session so a write failure surfaces clearly.
    if channel and proposed:
        save_overlay(channel, proposed)
        log.info(
            "self_improvement_prompt_applied",
            extra={"rec_id": rec_id, "channel": channel, "approved_by": approved_by},
        )
    return {"id": rec_id, "status": "approved", "channel": channel}


def reject_recommendation(rec_id: int, *, rejected_by: str) -> None:
    with session_scope() as session:
        rec = session.get(PromptRecommendation, rec_id)
        if rec is None:
            raise ValueError(f"Recommendation {rec_id} not found")
        rec.status = "rejected"
        rec.approved_by = rejected_by
        rec.approved_at = datetime.utcnow()


def save_as_draft(rec_id: int) -> None:
    with session_scope() as session:
        rec = session.get(PromptRecommendation, rec_id)
        if rec is None:
            raise ValueError(f"Recommendation {rec_id} not found")
        rec.status = "draft"


def rollback_recommendation(rec_id: int) -> dict[str, Any]:
    """Restore the previous_prompt_snapshot for an approved recommendation.

    Looks up the row, writes its previous_prompt_snapshot back to the
    prompt_configs overlay, and flips status to 'rejected'. Returns a
    summary dict so the UI can quote what changed.
    """
    with session_scope() as session:
        rec = session.get(PromptRecommendation, rec_id)
        if rec is None:
            raise ValueError(f"Recommendation {rec_id} not found")
        if not rec.channel or rec.previous_prompt_snapshot is None:
            raise ValueError("Nothing to roll back — no channel/snapshot stored.")
        channel = rec.channel
        previous = rec.previous_prompt_snapshot
        rec.status = "rejected"
    save_overlay(channel, previous)
    log.info("self_improvement_rolled_back", extra={"rec_id": rec_id, "channel": channel})
    return {"id": rec_id, "channel": channel}


# ---------------------------------------------------------------------------
# Experiment tracking — per-prompt-version rollup
# ---------------------------------------------------------------------------

def performance_by_prompt_version() -> list[dict[str, Any]]:
    """Per-prompt-version performance rollup for the experiment tracker.

    Rolls up sent / opened / replied / bounced counts grouped by
    GeneratedContent.prompt_version (with prompt_fingerprint as a
    tiebreaker so silent edits of the same version show as separate
    rows). Joins Engagement so only leads with a sync result count.
    """
    stmt = (
        select(
            GeneratedContent.prompt_version.label("prompt_version"),
            GeneratedContent.prompt_fingerprint.label("prompt_fingerprint"),
            func.count(Engagement.id).label("sent"),
            func.sum(case((Engagement.opened.is_(True), 1), else_=0)).label("opened"),
            func.sum(case((Engagement.replied.is_(True), 1), else_=0)).label("replied"),
            func.sum(case((Engagement.bounced.is_(True), 1), else_=0)).label("bounced"),
        )
        .select_from(GeneratedContent)
        .join(Engagement, Engagement.content_id == GeneratedContent.id)
        .where(
            GeneratedContent.kind == "email",
            Engagement.sent.is_(True),
        )
        .group_by(
            GeneratedContent.prompt_version,
            GeneratedContent.prompt_fingerprint,
        )
        .order_by(func.count(Engagement.id).desc())
    )
    with session_scope() as session:
        rows = session.execute(stmt).all()
    out: list[dict[str, Any]] = []
    for r in rows:
        sent = int(r.sent or 0)
        opened = int(r.opened or 0)
        replied = int(r.replied or 0)
        bounced = int(r.bounced or 0)
        denom = sent if sent > 0 else 1
        out.append({
            "prompt_version": r.prompt_version or "—",
            "prompt_fingerprint": (r.prompt_fingerprint or "")[:8] or "—",
            "sent": sent,
            "opened": opened,
            "replied": replied,
            "bounced": bounced,
            "open_rate": opened / denom,
            "reply_rate": replied / denom,
            "bounce_rate": bounced / denom,
            "low_confidence": sent < MIN_SAMPLE_FOR_RECOMMENDATION,
        })
    return out


def list_recommendations(limit: int = 20) -> list[dict[str, Any]]:
    """Most-recent PromptRecommendation rows for the audit log."""
    with session_scope() as session:
        rows = session.execute(
            select(PromptRecommendation)
            .order_by(PromptRecommendation.created_at.desc())
            .limit(limit)
        ).scalars().all()
        return [
            {
                "id": r.id,
                "bottleneck": r.bottleneck,
                "channel": r.channel,
                "diagnosis": r.diagnosis,
                "current_metric_label": r.current_metric_label,
                "current_metric_value": float(r.current_metric_value or 0.0),
                "target_metric_value": float(r.target_metric_value or 0.0),
                "recommended_change": r.recommended_change,
                "expected_impact": r.expected_impact,
                "risk_level": r.risk_level,
                "proposed_prompt": r.proposed_prompt,
                "previous_prompt_snapshot": r.previous_prompt_snapshot,
                "sample_size": int(r.sample_size or 0),
                "low_confidence": bool(r.low_confidence),
                "status": r.status,
                "approved_by": r.approved_by,
                "approved_at": r.approved_at,
                "created_at": r.created_at,
            }
            for r in rows
        ]
