[theme]
base = "light"
primaryColor = "#1F3DE5"
backgroundColor = "#FAF8F4"
secondaryBackgroundColor = "#F2EFE9"
textColor = "#0F0E0C"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
